docs/index.md
=> server intro updated

docs/design-challenge/challenges/week1.md, mkdocs.yml
=> w1 design challenge

docs/design-guide/stages/stage0/0C-navigation.md, docs/design-guide/stages/stage1/1A-sketchingPartDesign.md
just a bit of polishing of the text
=> polished cadvent section wording and removed a redundant phrase from 0C

mkdocs.yml
It was annoying for me to find this github repo.
=> add link to the git repo

docs/design-standards/pages/hardware-design-standards.md, docs/featurescripts.md, docs/index.md, mkdocs.yml
Fixed a thing in the homepage, added a note about supplier tolerance in best practices, fixed a weird space in the sidebar, and added a few new featurescripts
=> Polished some things

README.md, docs/contribution/methodsOfContributing.md
=> methods of contributing and readme

docs/resources/featurescripts.md
reorganized featurescripts into categories and added a few more
=> Reorganized featurescripts page

docs/design-guide/stage1/1A-onshapeFundamentals.md, docs/index.md
separated examples, added note about naming sketches, tip with links to help center
=> added notes and polished stuff in 1A

.github/workflows/ci.yaml, generate_mkdocs_config.py, mkdocs.base.yml, mkdocs.yml, runlocal.sh
=> removed git committers plugin

docs/design-challenge/challenges/week1.md, docs/design-challenge/challenges/week2.md, docs/design-challenge/challenges/week3.md, docs/design-challenge/challenges/week4.md, docs/design-challenge/challenges/week5.md, mkdocs.yml
added weeks 3-5, changed week 1 and 2, changed mkdocs.yml
=> attempt #2

docs/design-guide/stage1/1A-onshapeFundamentals.md
fixed the broken link for intro to sketching in 1a
=> updated intro to sketching link

docs/best-practices/assembly-setup.md, docs/best-practices/document-setup.md, docs/best-practices/feature-tree-setup.md, docs/best-practices/mastersketch-setup.md
fixed some grammar, added colored sketches, and link to part numbering featurescripts
=> best practices review

docs/design-fundamentals/structure/structure.md
grammar and other things said in the issue
=> fixed issue 204

docs/learning-course/stage1/1A-onshapeFundamentals.md
switched around practice exercise prereqs section
=> more 1A changes

docs/index.md, docs/learning-course/index.md, docs/learning-course/stage0/0B-setup.md, docs/learning-course/stage1/1A-onshapeFundamentals.md, docs/learning-course/stage1/1C-designMethodology.md, docs/website-feature-guide.md, mkdocs.yml
It's like the nice finishing touch
=> Homepage cards, website feature guide links, polishing

docs/contribution/contributors.md, docs/index.md
added kremer's first name, fixed home page button
=> contributors fix

docs/learning-course/stage2/2E-cascadeElevator.md
2H -> 2E
link is fixed to actually link to crush block page
=> fixed link and title

docs/index.md
Mkdocs doesn't transform absolute links
=> Fix absolute links on home page

docs/learning-course/stage1/1A/assembly.md, docs/learning-course/stage1/1A/exercise1.md, docs/learning-course/stage1/1A/exercise2.md, docs/learning-course/stage1/1A/multi-body.md, docs/learning-course/stage1/1B/belts.md, docs/learning-course/stage1/1B/chain.md, docs/learning-course/stage1/1B/gears.md, docs/learning-course/stage1/1B/introduction.md, docs/learning-course/stage1/1B/motors.md, docs/learning-course/stage1/1B/shafts-bearings.md, docs/learning-course/stage1/1D/introduction.md, docs/learning-course/stage1/1D/project-overview.md, docs/learning-course/stage1/1D/top-down-design.md, docs/learning-course/stage1/1E/battery-mounting.md, docs/learning-course/stage1/1E/electronics.md, docs/learning-course/stage1/1E/exercise2.md, docs/learning-course/stage1/1E/exercise5.md, docs/learning-course/stage1/1E/project-overview.md
updated figure formatting and added photocredits
=> Photo credits

docs/learning-course/stage1/1A/exercise-setup.md, docs/learning-course/stage1/1B/exercise1.md, docs/learning-course/stage1/1C/exercise-overview.md, docs/learning-course/stage1/1D/project-overview.md, docs/learning-course/stage1/1E/project-overview.md, docs/learning-course/stage2/2A/project-overview.md, docs/learning-course/stage2/2B/project-overview.md, docs/learning-course/stage2/2C/project-overview.md, docs/learning-course/stage2/2D/project-overview.md, docs/website-feature-guide.md
Signed-off-by: Jonathan Mi <jonathan.mi6@gmail.com>
=> Onshape-link-updates
